name: Build RatioJuris Releases

on:
  release:
    types: [created]
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: jfc_config-win64.exe
            asset_name: jfc_config-win64.exe
          - os: ubuntu-latest
            artifact_name: jfc_config-linux
            asset_name: jfc_config-linux
          - os: macos-latest
            artifact_name: jfc_config-macos
            asset_name: jfc_config-macos

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          architecture: 'x64'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests urllib3 pyfiglet

      - name: Build Executable
        run: |
          pyinstaller --distpath ./build --workpath ./build/temp --onefile --collect-all pyfiglet --name ${{ matrix.artifact_name }} ./src/jfc_config.py

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
